name: Stoplight Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: publish
      run: |
        yarn
        pwd
        ls -la
        yarn run publish
      env:
        CI: true
